### ISSUE TITLE
multiple sources va WABS_SRC

### ISSUE THREAD

**Issue by tomdavidson** [byu-oit-appdev/wabs#12]
Allow setting multiple sources via the env var config such that the following example would be a legitimate configuration:

WABS_SRC=http://website.endpoint1.com:/,http://website.endpoint2.com/master:/next

related to #11

**Comment by Gi60s** [comment]
Feature enabled. You'll need to use a colon to separate values. If you need colon characters within your value you'll need to use quotes to wrap the values.

WABS_SRC='"http://website.endpoint1.com:/":"http://website.endpoint2.com/master:next"'
