### ISSUE TITLE
route via WABS_SRC does not work

### ISSUE THREAD

**Issue by tomdavidson** [byu-oit-appdev/wabs#9]
when trying to route / to master/   i end up with 404 and wabs log shows:
```
[REQUEST] : 302 : 0.001 : / => https://cas.byu.edu/cas/login?gateway=true&service=https%3A%2F%2Fwabsng.autoreg.byu.edu%2Fwabs%2Fauth%2Fcas-ticket%3Fredirect%3Dhttps%3A%2F%2Fwabsng.autoreg.byu.edu%2F
[REQUEST] : 302 : 0.001 : /wabs/auth/cas-ticket?redirect=https://wabsng.autoreg.byu.edu/ => https://wabsng.autoreg.byu.edu/
```

I have tired:
http://autoreg-webapp-website.s3-website-us-west-2.amazonaws.com:/master
http://autoreg-webapp-website.s3-website-us-west-2.amazonaws.com/:/master
http://autoreg-webapp-website.s3-website-us-west-2.amazonaws.com:master/
http://autoreg-webapp-website.s3-website-us-west-2.amazonaws.com/:master/

works fine when the app is placed in the webroot and WAB_SRC is set to http://autoreg-webapp-website.s3-website-us-west-2.amazonaws.com

**Comment by Gi60s** [comment]
Just to make sure you're understanding the src correctly. Say you have a domain http://foo.com that is running WABS. By providing the src as `http://autoreg-webapp-website.s3-website-us-west-2.amazonaws.com:/master` what you are saying is that when the client / browser makes a request to http://foo.com/master it should send the request to `http://autoreg-webapp-website.s3-website-us-west-2.amazonaws.com`. Is that how you're using the src option?

**Comment by Gi60s** [comment]
Misunderstanding of functionality confirmed.
